### ISSUE TITLE
Embed Links Not Working

### ISSUE THREAD

**Issue by LPCoderAu** [ProjectOpenSea/embeddable-nfts#26] opened 2021-05-17 11:46 UTC
Hi,

It appears that the embed links are not working for NFTs on the Matic/Polygon network. I am consistently getting an error trying to load them. Is it possible to get a fix soon, I have a front end waiting to be populated?

Works fine with NFTs on the main ETH chain

Thanks

**Comment by Saw-mon-and-Natalie** [comment] 2021-06-04 05:57
Having the same issue. Here is an example (also on [codepen](https://codepen.io/sawmon_and_natalie/pen/rNydJoY)):

```html
 <nft-card
    contractAddress="0x36a8377e2bb3ec7d6b0f1675e243e542eb6a4764"
    tokenId="832">
</nft-card>
<script src="https://unpkg.com/embeddable-nfts/dist/nft-card.min.js"></script>
```

The NFT page on OpenSea:
https://opensea.io/assets/matic/0x36a8377e2bb3ec7d6b0f1675e243e542eb6a4764/815

**Comment by Saw-mon-and-Natalie** [comment] 2021-06-04 06:48
Looking at the [nft-card.ts](https://github.com/ProjectOpenSea/embeddable-nfts/blob/master/src/nft-card.ts) and checking out [opensea-js/src/seaport.ts](https://github.com/ProjectOpenSea/opensea-js/blob/master/src/seaport.ts) looks like only `mainnet` and `rinkeby` networks are supported.

**Comment by geauxedits** [comment] 2021-11-21 13:14
I can confirm this is an issue. Used embed code for an item listed on POLY did not work. Used embed code with item listed on ETH and the embed worked. Anyone find a work around? TIA!

**Comment by fafrd** [comment] 2021-12-01 21:51
Duplicate of https://github.com/ProjectOpenSea/embeddable-nfts/issues/37

**Closed by fafrd** 2021-12-01 21:51 UTC

**Comment by biblepay** [comment] 2022-01-09 19:15
Please, is there a way to bring this feature back to the forefront or a possible workaround for polygon?

As I just coded our core wallet web site to support opensea embeds, but they are polygon only.  We could really use the ability to display these embed nfts.  

Thanks.

**Comment by dzhsurf** [comment] 2022-01-13 08:04
+1
Please, is there a way to bring this feature back to the forefront or a possible workaround for polygon?

As I just coded our core wallet web site to support opensea embeds, but they are polygon only. We could really use the ability to display these embed nfts.

Thanks.
