### ISSUE TITLE
orientationMode="auto"

### ISSUE THREAD

**Issue by ajraymond27** [ProjectOpenSea/embeddable-nfts#24] opened 2021-05-10 23:22 UTC
This input doesn't work responsively: orientationMode="auto"
It only converts to vertical view on a hard refresh after breaking width of 600px. Would be great to make this more responsive

**Comment by fafrd** [comment] 2021-12-02 17:43
Closing as duplicate of #20

**Closed by fafrd** 2021-12-02 17:43 UTC
